version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/home/boris/core-repos/food-delivery-app/docker/volumes/rabbitmq/data

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: delivery_admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: food_delivery
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/home/boris/core-repos/food-delivery-app/docker/volumes/postgresql/data

volumes:
  rabbitmq_data:
  postgres_data:
